spring.application.name=product-service
spring.mongodb.uri=mongodb://root:password@localhost:27017/product-service?authSource=admin

#默认就会提供：
#OpenAPI JSON:
#http://localhost:8080/v3/api-docs
#
#Swagger UI:
#http://localhost:8080/swagger-ui.html
springdoc.swagger-ui.path=/swagger-ui.html